spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MyLobin/microservice
          searchPaths: cfg
#          username:
#          password:
#  rabbitmq:
#    host: 192.168.0.111
#    port: 5672
#    username: admin
#    password: admin
server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/
