spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MyLobin/Java-Learning/
          searchPaths: microservice/config-repo
#          username:
#          password:
server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/
